services:
  web:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./badplace:/badplace
    env_file: badplace/.env
    command: python manage.py runserver 0.0.0.0:8000